### ISSUE TITLE
Add version update notification

### ISSUE THREAD

**Issue by sondreb** [block-core/ariton#8]
Reference: https://senoritadeveloper.medium.com/notify-users-with-the-new-version-of-your-angular-app-56813b24d8e3

**Comment by sondreb** [comment]
For future reference, this is the original ngsw-config.json that until later, we will change to make sure it loads latest version and don't get into caching issues:

```
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "Ariton",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/**/*.(svg|cur|jpg|jpeg|png|apng|webp|avif|gif|otf|ttf|woff|woff2)"
        ]
      }
    }
  ]
}
```

**Comment by sondreb** [comment]
<img width="374" alt="Screenshot 2024-07-06 at 12 53 07" src="https://github.com/block-core/ariton/assets/309938/df559365-c53f-461a-bbb6-99fd328bb0e1">

**Comment by sondreb** [comment]
Also doing this: https://blog.stackademic.com/cache-busting-in-angular-378d1877302b

**Comment by dangershony** [comment]
I think this is important and it must also be a prompt not an auto update

**Comment by sondreb** [comment]
![image](https://github.com/block-core/ariton/assets/309938/dabdcedd-805e-4a4a-bb7d-d6225580063c)

This is how it has been implemented now, the update icon appears that user can click to quickly reload the app. Closing this issue for now, this is good enough for now.
